name: Push to Dev

on:
  push:
    branches:
      - main  # or the branch you want to track

jobs:
  notify-qa:
    runs-on: ubuntu-latest

    steps:
    - name: Send event to QA repository
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://github.com/Tamilcodoidd/Letz-watch/dispatches \
        -d '{"event_type":"dev_push", "client_payload":{}}'
