name: Deploy and Test

on:
  push:
    branches:
      - main  # Change to your development branch

jobs:
  deploy-and-trigger-qa:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to development environment
      run: |
        echo "Deploying to development environment..."
        # Add your deployment script/command here

    - name: Trigger QA repository workflow
      env:
        NGITHUB_TOKEN: ${{ secrets.NGITHUB_TOKEN }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $NGITHUB_TOKEN" \
          https://api.github.com/repos/Tamilcodoidd/Letz-watch/dispatches \
          -d '{"event_type":"run-qa-tests"}'
